name = "qrdurian-trace"
main = "worker.js"
compatibility_date = "2026-06-01"
routes = [{ pattern = "trace.qrdurian.com", custom_domain = true }]

[[d1_databases]]
binding = "DB"
database_name = "qrdurian-trace"
database_id = "92dfaa4b-7c50-4232-b715-9ea8a322d19a"

# optional — orchard photos
# [[r2_buckets]]
# binding = "PHOTOS"
# bucket_name = "qrdurian-photos"
